name: dark_mode
description: Add the ability to toggle dark mode.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true